name: Debugging with SSH
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        uses: wskmcserver1/action-ssh@master
      - name: Sleep
        run: sleep 1h
